site_name: NILTC
docs_dir: mkdocs/docs
site_dir: mkdocs/site

theme:
  name: material
  logo: assets/niltc_banner.png
  favicon: assets/favicon.jpg
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
  font:
    text: Open Sans
    code: Consolas

plugins:
  - search

hooks:
  - mkdocs/hooks.py

extra_css:
  - stylesheets/niltc.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/NILTC
      name: NILTC on Facebook
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/niltc/
      name: NILTC on Instagram
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCMU0Eiw6H903-Lgzayy_yVQ
      name: NILTC on YouTube
    - icon: fontawesome/brands/flickr
      link: https://www.flickr.com/groups/1797131@N23/
      name: NILTC on Flickr

copyright: 'Contact: <a href="mailto:niltc.contact@gmail.com">niltc.contact@gmail.com</a>'

nav:
  - NILTC:
      - Welcome to NILTC: index.md
      - About: about/index.md
      - Membership: membership/index.md
      - In the News: in-the-news/index.md
      - FAQs: faqs/index.md
  - Shows:
      - Upcoming Shows: upcoming-shows/index.md
      - Past Shows:
          - Overview: past-shows/index.md
          - 2020s: past-shows/2020s/index.md
          - 2010s: past-shows/2010s/index.md
      - Pictures and Videos: pictures-and-videos/index.md
      - Castle: castle/index.md
  - Standards:
      - Overview: standards/index.md
      - Themes: standards/themes/index.md
      - Train Specifications: standards/train-specifications/index.md
      - Track Specifications: standards/track-specifications/index.md
      - Power Distribution Through Brick Built Roads: standards/power-distribution-through-brick-built-roads/index.md
      - Plexiglas: standards/plexiglas/index.md
      - Skirting: standards/skirting/index.md
      - Tables: standards/tables/index.md
      - Skyscrapers: standards/skyscrapers/index.md
